security:
    password_hashers:
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'auto'
        App\Entity\Admin:
            algorithm: auto

    providers:
        app_user_provider:
            entity:
                class: App\Entity\User
                property: email

        # Either add the missing provider definition here:
        app_admin_provider:
            entity:
                class: App\Entity\Admin  # Adjust this to your actual Admin entity
                property: email  # Adjust this to your admin's username property

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        admin:
            pattern: ^/admin
            provider: app_user_provider
            form_login:
                login_path: admin_login
                check_path: admin_login
                default_target_path: sonata_admin_dashboard
                username_parameter: _email
                enable_csrf: true
            logout:
                path: admin_logout
                target: admin_login
            remember_me:
                secret: '%kernel.secret%'
                lifetime: 604800 # 1 week
            switch_user:
                role: ROLE_ALLOWED_TO_SWITCH
                parameter: _switch_user

        main:
            lazy: true
            provider: app_admin_provider  # Make sure this matches a defined provider
            # Other main firewall settings

    role_hierarchy:
        ROLE_ADMIN: [ ROLE_USER ]
        ROLE_PRODUCT_ADMIN: [ ROLE_ADMIN ]
        ROLE_CUSTOMER_ADMIN: [ ROLE_ADMIN ]
        ROLE_ORDER_ADMIN: [ ROLE_ADMIN ]
        ROLE_CONTENT_ADMIN: [ ROLE_ADMIN ]
        ROLE_SUPER_ADMIN: [
            ROLE_ADMIN,
            ROLE_PRODUCT_ADMIN,
            ROLE_CUSTOMER_ADMIN,
            ROLE_ORDER_ADMIN,
            ROLE_CONTENT_ADMIN,
            ROLE_ALLOWED_TO_SWITCH
        ]

    access_control:
        - { path: ^/admin/login$, role: PUBLIC_ACCESS }
        - { path: ^/admin/, role: ROLE_ADMIN }