security:
    password_hashers:
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'auto'
        App\Entity\Admin:
            algorithm: auto

    providers:
        app_user_provider:
            entity:
                class: App\Entity\User
                property: email

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        admin:
            pattern: ^/admin
            provider: app_user_provider
            form_login:
                login_path: admin_login
                check_path: admin_login
                default_target_path: sonata_admin_dashboard
                username_parameter: _email
                csrf_token_generator: security.csrf.token_manager
            logout:
                path: admin_logout
                target: admin_login
            remember_me:
                secret: '%kernel.secret%'
                lifetime: 604800 # 1 week
            switch_user:
                role: ROLE_ALLOWED_TO_SWITCH
                parameter: _switch_user

        role_hierarchy:
            ROLE_ADMIN: [ ROLE_USER ]
            ROLE_PRODUCT_ADMIN: [ ROLE_ADMIN ]
            ROLE_CUSTOMER_ADMIN: [ ROLE_ADMIN ]
            ROLE_ORDER_ADMIN: [ ROLE_ADMIN ]
            ROLE_CONTENT_ADMIN: [ ROLE_ADMIN ]
            ROLE_SUPER_ADMIN: [
                ROLE_ADMIN,
                ROLE_PRODUCT_ADMIN,
                ROLE_CUSTOMER_ADMIN,
                ROLE_ORDER_ADMIN,
                ROLE_CONTENT_ADMIN,
                ROLE_ALLOWED_TO_SWITCH
            ]

        main:
            lazy: true
            provider: app_admin_provider  # Changed from users_in_memory
            # Other main firewall settings

    access_control:
        - { path: ^/admin/login$, role: PUBLIC_ACCESS }  # Updated from IS_AUTHENTICATED_ANONYMOUSLY
        - { path: ^/admin/, role: ROLE_ADMIN }