sonata_admin:
  title: 'Sonata Admin'
  title_logo: 'bundles/sonataadmin/logo_title.png'
  options:
    html5_validate: true
    confirm_exit: true
    use_select2: true
    use_icheck: true
    pager_links: 5
  templates:
    layout: 'admin/layout.html.twig'
  dashboard:
    blocks:
      -
        position: top
        class: col-md-12
        type: sonata.admin.block.stats
        settings:
          code: app.admin.user  # Changed from admin_code to code
      -
        position: left
        type: sonata.admin.block.admin_list
        settings:
          groups: [Users, Content]
      -
        position: right
        type: sonata.admin.block.admin_list
        settings:
          groups: [Security]
    # Rest of your configuration remains the same