sonata_admin:
  title: 'Sonata Admin'
  title_logo: 'bundles/sonataadmin/logo_title.png'
  options:
    html5_validate: true
    confirm_exit: true
    use_select2: true
    use_icheck: true
    pager_links: 5
  templates:
    layout: 'admin/layout.html.twig'
  dashboard:
    blocks:
      -
        position: top
        class: col-md-12
        type: sonata.admin.block.stats
      -
        position: left
        type: sonata.admin.block.admin_list
        settings:
          groups: [Users, Content]
      -
        position: right
        type: sonata.admin.block.admin_list
        settings:
          groups: [Security]
    groups:
      Users:
        label: Users
        label_catalogue: SonataAdminBundle
        icon: '<i class="fa fa-users"></i>'
        items:
          - app.admin.user
      Security:
        label: Security
        label_catalogue: SonataAdminBundle
        icon: '<i class="fa fa-lock"></i>'
        items:
          - app.admin.impersonation_log
      Content:
        label: Content
        label_catalogue: SonataAdminBundle
        icon: '<i class="fa fa-file-text"></i>'
        items: []