version: '3.8'

services:
  php:
    build:
      context: ./.docker/php
    volumes:
      - ./:/var/www/html
      - ~/.composer:/root/.composer
    environment:
      - APP_ENV=${APP_ENV:-dev}
      - APP_DEBUG=${APP_DEBUG:-1}
      - DATABASE_URL=mysql://sonata:sonata@db:3306/sonata_admin?serverVersion=8.0

  nginx:
    build:
      context: ./.docker/nginx
    volumes:
      - ./:/var/www/html
      - ./.docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "${NGINX_PORT:-8080}:80"
    depends_on:
      - php

  db:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=sonata_admin
      - MYSQL_USER=sonata
      - MYSQL_PASSWORD=sonata
    volumes:
      - db-data:/var/lib/mysql
      - ./.docker/mysql/my.cnf:/etc/mysql/conf.d/my.cnf
    ports:
      - "${DB_PORT:-3306}:3306"

  mailhog:
    image: mailhog/mailhog
    ports:
      - "${MAILHOG_PORT:-8025}:8025"

volumes:
  db-data: