# Authentication routes
admin_login:
    path: /admin/login
    controller: App\Controller\SecurityController::login

admin_logout:
    path: /admin/logout
    controller: App\Controller\SecurityController::logout

# Sonata Admin core routes
admin_area:
    resource: "@SonataAdminBundle/Resources/config/routing/sonata_admin.xml"
    prefix: /admin

_sonata_admin:
    resource: .
    type: sonata_admin
    prefix: /admin